#!/usr/bin/env bash


##########################################################################
#
#         IN DEVELOPMENT  IN DEVELOPMENT  IN DEVELOPMENT  IN DEVELOPMENT
#         IN DEVELOPMENT  IN DEVELOPMENT  IN DEVELOPMENT  IN DEVELOPMENT
#
##########################################################################



# Copyright 03/20/2016 Aaron Caffrey https://github.com/wifiextender

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.


find /tmp/re/datest -type f -neweram /tmp/re/datest2/ &> /dev/null

[[ $? == 0 ]] && {

    cd /tmp/re/datest

    # make the dirs
    find . -type d -print0|xargs -0 -I{} mkdir -p /tmp/re/datest2/{}

    # encrypt the changed/newer files
    find . -type f -neweram /tmp/re/datest2/ -print0|\
        xargs -0 -I{} /home/frost/skilcrypt encrypt pwf /tmp/pws {}

    # move them
    find . -type f -name "*.gpg" -print0|\
        xargs -0 -I{} mv --force {} /tmp/re/datest2/{}

}
